import { useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Building2, LogOut, UserPlus } from 'lucide-react'
import { supabase } from './lib/supabase'
import './team-access.css'

const db=supabase as any
const PRODUCTION_URL='https://northborn.vercel.app'
type Details={organization_name:string;customer_name:string;invite_status:string;invite_expires_at:string}
const readError=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message||e||'Something went wrong')
function redirect(path:string){const base=window.location.hostname.endsWith('vercel.app')?PRODUCTION_URL:window.location.origin;return `${base}${path}`}

export default function ClientJoinPage(){
 const token=new URLSearchParams(window.location.search).get('invite')||''
 const [details,setDetails]=useState<Details|null>(null),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[mode,setMode]=useState<'signin'|'signup'>('signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false)
 const path=`/client-join?invite=${encodeURIComponent(token)}`
 useEffect(()=>{let active=true;const load=async()=>{if(!token){setMessage('This client invite is missing its invite code.');setLoading(false);return}const [s,i]=await Promise.all([supabase.auth.getSession(),db.rpc('get_customer_portal_invite_details',{_token:token})]);if(!active)return;setSession(s.data.session);if(i.error)setMessage(i.error.message);else setDetails(i.data?.[0]||null);setLoading(false)};void load();const {data:l}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>{active=false;l.subscription.unsubscribe()}},[token])
 const emailAuth=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const r=mode==='signin'?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:redirect(path)}});if(r.error)throw r.error;if(mode==='signup'&&!r.data.session)setMessage('Check your email to confirm your Northborn account, then return to this invitation.')}catch(err){setMessage(readError(err))}finally{setBusy(false)}}
 const google=async()=>{setBusy(true);setMessage('');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect(path)}});if(error){setMessage(error.message);setBusy(false)}}
 const accept=async()=>{setBusy(true);setMessage('');try{const r=await db.rpc('accept_customer_portal_invite',{_token:token});if(r.error)throw r.error;window.location.href='/'}catch(err){setMessage(readError(err));setBusy(false)}}
 const signOut=async()=>{await supabase.auth.signOut();setSession(null);setMessage('')}
 const expired=details?new Date(details.invite_expires_at).getTime()<=Date.now():false;const inactive=details&&(details.invite_status!=='pending'||expired)
 if(loading)return <div className="team-page team-center">Loading client invitation…</div>
 return <div className="team-page team-center join-page"><div className="team-card join-card"><div className="join-icon"><Building2 size={30}/></div><div className="team-eyebrow">NORTHBORN CLIENT PORTAL</div><h1>{details?.customer_name?`Access ${details.customer_name}`:'Client portal invitation'}</h1>{details&&<p><strong>{details.organization_name}</strong> invited you to manage your company profile and contacts.</p>}{inactive&&<div className="team-error">This invitation is {expired?'expired':details?.invite_status}.</div>}{message&&<div className="team-message">{message}</div>}{!details&&!message&&<div className="team-error">Invite not found.</div>}{details&&!inactive&&!session&&<><button className="google-join" disabled={busy} onClick={()=>void google()}><span>G</span>Continue with Google</button><div className="join-divider"><span>or</span></div><form className="team-form" onSubmit={emailAuth}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="join-password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='signup'?8:1} required/><button type="button" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div></label><button className="team-primary" disabled={busy}>{busy?'Working…':mode==='signup'?'Create account':'Sign in'}</button></form><button className="join-switch" onClick={()=>{setMode(mode==='signup'?'signin':'signup');setMessage('')}}>{mode==='signup'?'Already have an account? Sign in':'Need an account? Create one'}</button></>}{details&&!inactive&&session&&<div className="team-form accept-box"><UserPlus size={30}/><div><strong>Connect your client portal</strong><p>Signed in as {session.user.email}. This account will only get access to {details.customer_name}.</p></div><button className="team-primary" disabled={busy} onClick={()=>void accept()}>{busy?'Connecting…':`Open ${details.customer_name} portal`}</button><button type="button" className="join-signout" onClick={()=>void signOut()}><LogOut size={16}/>Use a different account</button></div>}<a className="join-home" href="/">Return to Northborn</a></div></div>
}
