import { useCallback, useEffect, useMemo, useState } from 'react'
import { Bell, FileText, MapPin, Save, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import './pack3-client-resources.css'

const db=supabase as any
type Site={id:string;name:string;address:string|null;access_directions:string|null;purchase_order:string|null;afe_number:string|null;status:string}
type Doc={id:string;file_name:string;storage_path:string;category:string;description:string|null;created_at:string}
type Notice={id:string;title:string;message:string|null;read_at:string|null;created_at:string}
type Profile={billing_address:string;default_purchase_order:string;default_afe_number:string;payment_terms:string;portal_notes:string}
const EMPTY:Profile={billing_address:'',default_purchase_order:'',default_afe_number:'',payment_terms:'',portal_notes:''}
const readError=(e:unknown)=>e instanceof Error?e.message:String((e as any)?.message||e||'Something went wrong.')

export default function ClientCustomerResources({customerId,portalRole,onMessage}:{customerId:string;portalRole:string;onMessage:(message:string)=>void}){
 const [profile,setProfile]=useState<Profile>(EMPTY),[sites,setSites]=useState<Site[]>([]),[docs,setDocs]=useState<Doc[]>([]),[notices,setNotices]=useState<Notice[]>([]),[siteOpen,setSiteOpen]=useState(false),[busy,setBusy]=useState(false)
 const [site,setSite]=useState({id:'',name:'',address:'',access_directions:'',purchase_order:'',afe_number:''})
 const isAdmin=portalRole==='admin',canEditSites=['admin','operations'].includes(portalRole)
 const load=useCallback(async()=>{
  const [p,s,d,n]=await Promise.all([
   db.rpc('get_my_customer_profile',{_customer_id:customerId}),
   db.from('customer_sites').select('id,name,address,access_directions,purchase_order,afe_number,status').eq('customer_id',customerId).eq('status','active').order('name'),
   db.from('customer_documents').select('id,file_name,storage_path,category,description,created_at').eq('customer_id',customerId).eq('visible_to_client',true).order('created_at',{ascending:false}),
   db.from('user_notifications').select('id,title,message,read_at,created_at').order('created_at',{ascending:false}).limit(12),
  ])
  const bad=[p,s,d,n].find(x=>x.error)?.error;if(bad)onMessage(bad.message)
  const row=p.data?.[0];if(row)setProfile({billing_address:row.billing_address||'',default_purchase_order:row.default_purchase_order||'',default_afe_number:row.default_afe_number||'',payment_terms:row.payment_terms||'',portal_notes:row.portal_notes||''})
  setSites(s.data||[]);setDocs(d.data||[]);setNotices(n.data||[])
 },[customerId,onMessage])
 useEffect(()=>{void load()},[load])

 const saveProfile=async()=>{setBusy(true);const r=await db.rpc('update_my_customer_profile',{_customer_id:customerId,_billing_address:profile.billing_address,_default_purchase_order:profile.default_purchase_order,_default_afe_number:profile.default_afe_number,_payment_terms:profile.payment_terms,_portal_notes:profile.portal_notes});if(r.error)onMessage(r.error.message);else{onMessage('Billing preferences updated.');await load()}setBusy(false)}
 const editSite=(row?:Site)=>{setSite(row?{id:row.id,name:row.name,address:row.address||'',access_directions:row.access_directions||'',purchase_order:row.purchase_order||'',afe_number:row.afe_number||''}:{id:'',name:'',address:'',access_directions:'',purchase_order:'',afe_number:''});setSiteOpen(true)}
 const saveSite=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');const payload={customer_id:customerId,name:site.name.trim(),address:site.address.trim()||null,access_directions:site.access_directions.trim()||null,purchase_order:site.purchase_order.trim()||null,afe_number:site.afe_number.trim()||null,status:'active'};let r;if(site.id)r=await db.from('customer_sites').update(payload).eq('id',site.id).eq('customer_id',customerId);else{const ctx=await db.rpc('get_my_customer_portal_context');const org=ctx.data?.find((x:any)=>x.customer_id===customerId)?.organization_id;if(!org)throw new Error('Client workspace unavailable');r=await db.from('customer_sites').insert({...payload,organization_id:org,created_by:u.user.id})}if(r.error)throw r.error;setSiteOpen(false);await load()}catch(e){onMessage(readError(e))}finally{setBusy(false)}}
 const openDoc=async(row:Doc)=>{const r=await supabase.storage.from('customer-documents').createSignedUrl(row.storage_path,120);if(r.error)onMessage(r.error.message);else window.open(r.data.signedUrl,'_blank','noopener,noreferrer')}
 const unread=useMemo(()=>notices.filter(n=>!n.read_at).length,[notices])

 return <>
  <section id="client-sites" className="portal-card"><div className="portal-card-head row"><div className="portal-head-copy"><MapPin/><div><strong>Sites and locations</strong><span>Saved locations and job reference information</span></div></div>{canEditSites&&<button className="portal-secondary" onClick={()=>editSite()}>Add site</button>}</div><div className="pack3-site-list">{sites.map(row=><button type="button" className="pack3-site-row" key={row.id} onClick={()=>canEditSites&&editSite(row)}><MapPin size={17}/><span><strong>{row.name}</strong><small>{row.address||'No address'}{row.purchase_order?' · PO '+row.purchase_order:''}{row.afe_number?' · AFE '+row.afe_number:''}</small>{row.access_directions&&<em>{row.access_directions}</em>}</span></button>)}{!sites.length&&<div className="portal-empty">No saved sites yet.</div>}</div></section>
  <section id="client-documents" className="portal-card"><div className="portal-card-head"><FileText/><div><strong>Documents</strong><span>Files your service provider has shared with you</span></div></div><div className="pack3-document-list">{docs.map(row=><div className="pack3-document-row client" key={row.id}><FileText size={17}/><button type="button" onClick={()=>void openDoc(row)}><strong>{row.file_name}</strong><small>{row.category.replaceAll('_',' ')}{row.description?' · '+row.description:''}</small></button></div>)}{!docs.length&&<div className="portal-empty">No shared documents yet.</div>}</div></section>
  <section id="client-billing-profile" className="portal-card"><div className="portal-card-head"><FileText/><div><strong>Billing and references</strong><span>Defaults your team uses for new work and billing</span></div></div><label>Billing address<textarea value={profile.billing_address} onChange={e=>setProfile({...profile,billing_address:e.target.value})} disabled={!isAdmin}/></label><div className="pack3-grid two"><label>Default PO<input value={profile.default_purchase_order} onChange={e=>setProfile({...profile,default_purchase_order:e.target.value})} disabled={!isAdmin}/></label><label>Default AFE<input value={profile.default_afe_number} onChange={e=>setProfile({...profile,default_afe_number:e.target.value})} disabled={!isAdmin}/></label></div><label>Payment terms<input value={profile.payment_terms} onChange={e=>setProfile({...profile,payment_terms:e.target.value})} disabled={!isAdmin}/></label><label>Shared account notes<textarea value={profile.portal_notes} onChange={e=>setProfile({...profile,portal_notes:e.target.value})} disabled={!isAdmin}/></label>{isAdmin&&<button className="portal-primary" disabled={busy} onClick={()=>void saveProfile()}><Save size={15}/>Save billing defaults</button>}</section>
  <section id="client-notifications" className="portal-card"><div className="portal-card-head"><Bell/><div><strong>Portal updates</strong><span>{unread?unread+' unread notification'+(unread===1?'':'s'):'Recent client notifications'}</span></div></div><div className="pack3-notice-list">{notices.map(row=><div className={!row.read_at?'unread':''} key={row.id}><span><strong>{row.title}</strong>{row.message&&<small>{row.message}</small>}</span><time>{new Date(row.created_at).toLocaleDateString('en-CA')}</time></div>)}{!notices.length&&<div className="portal-empty">No portal updates yet.</div>}</div></section>
  {siteOpen&&<div className="portal-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSiteOpen(false)}}><form className="portal-modal" onSubmit={saveSite}><div className="portal-modal-head"><strong>{site.id?'Edit site':'Add site'}</strong><button type="button" onClick={()=>setSiteOpen(false)}><X size={18}/></button></div><label>Site name<input value={site.name} onChange={e=>setSite({...site,name:e.target.value})} required/></label><label>Address<input value={site.address} onChange={e=>setSite({...site,address:e.target.value})}/></label><label>Access directions<textarea value={site.access_directions} onChange={e=>setSite({...site,access_directions:e.target.value})}/></label><div className="pack3-grid two"><label>PO<input value={site.purchase_order} onChange={e=>setSite({...site,purchase_order:e.target.value})}/></label><label>AFE<input value={site.afe_number} onChange={e=>setSite({...site,afe_number:e.target.value})}/></label></div><div className="portal-modal-actions"><button type="button" className="portal-secondary" onClick={()=>setSiteOpen(false)}>Cancel</button><button className="portal-primary" disabled={busy}>Save site</button></div></form></div>}
 </>
}
