import { useCallback, useEffect, useState } from 'react'
import { Building2, LogOut, Mail, Pencil, Phone, Plus, Trash2, UserRound, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import './client-portal.css'

const db=supabase as any
const TYPES=['field','supervisor','dispatch','office','billing','accounting','other'] as const
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const readError=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message||e||'Something went wrong.')

type Context={portal_user_id:string;organization_id:string;organization_name:string;customer_id:string;customer_name:string;customer_phone:string|null;customer_address:string|null;billing_email:string|null;portal_role:string}
type Contact={id:string;name:string;title:string|null;phone:string|null;email:string|null;contact_type:string;status:string;updated_at:string}

export default function ClientPortalApp({initialContext}:{initialContext:Context}){
 const [ctx,setCtx]=useState(initialContext),[contacts,setContacts]=useState<Contact[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[editor,setEditor]=useState<Contact|null|undefined>(undefined)
 const [company,setCompany]=useState({name:ctx.customer_name,phone:ctx.customer_phone||'',address:ctx.customer_address||'',billing_email:ctx.billing_email||''})
 const load=useCallback(async()=>{const [c,r]=await Promise.all([db.rpc('get_my_customer_portal_context'),db.rpc('get_my_customer_contacts',{_customer_id:ctx.customer_id})]);if(c.error){setMessage(c.error.message);setLoading(false);return}const next=(c.data||[]).find((x:any)=>x.customer_id===ctx.customer_id)||c.data?.[0];if(next){setCtx(next);setCompany({name:next.customer_name,phone:next.customer_phone||'',address:next.customer_address||'',billing_email:next.billing_email||''})}if(r.error)setMessage(r.error.message);else setContacts(r.data||[]);setLoading(false)},[ctx.customer_id])
 useEffect(()=>{void load()},[load])
 const saveCompany=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');const r=await db.rpc('update_my_customer_portal_company',{_customer_id:ctx.customer_id,_name:company.name.trim(),_phone:company.phone.trim(),_address:company.address.trim(),_billing_email:company.billing_email.trim()});if(r.error)setMessage(r.error.message);else{setMessage('Company information updated.');await load()}setBusy(false)}
 const archive=async(id:string)=>{if(!confirm('Remove this contact?'))return;setBusy(true);const r=await db.rpc('archive_my_customer_contact',{_customer_id:ctx.customer_id,_contact_id:id});if(r.error)setMessage(r.error.message);else await load();setBusy(false)}
 const signOut=async()=>{await supabase.auth.signOut();window.location.href='/'}
 if(loading)return <div className="portal-loading">Loading client portal…</div>
 return <div className="portal-shell"><header className="portal-header"><div className="portal-brand"><div>N</div><span><strong>NORTHBORN</strong><small>Client Portal</small></span></div><button onClick={()=>void signOut()}><LogOut size={17}/>Sign out</button></header><main className="portal-page"><div className="portal-hero"><span>CLIENT PORTAL</span><h1>{ctx.customer_name}</h1><p>Manage the company and contact information your service provider uses for jobs and billing.</p><small>Connected through {ctx.organization_name}</small></div>{message&&<div className="portal-message">{message}</div>}<div className="portal-layout"><form className="portal-card" onSubmit={saveCompany}><div className="portal-card-head"><Building2/><div><strong>Company information</strong><span>Main company details</span></div></div><label>Company name<input value={company.name} onChange={e=>setCompany({...company,name:e.target.value})} required/></label><label>Main phone<input value={company.phone} onChange={e=>setCompany({...company,phone:e.target.value})}/></label><label>Address<input value={company.address} onChange={e=>setCompany({...company,address:e.target.value})}/></label><label>Billing email<input type="email" value={company.billing_email} onChange={e=>setCompany({...company,billing_email:e.target.value})}/></label>{ctx.portal_role==='admin'&&<button className="portal-primary" disabled={busy}>Save company</button>}</form><section className="portal-card contacts-card"><div className="portal-card-head row"><div className="portal-head-copy"><UserRound/><div><strong>Contacts</strong><span>Field, dispatch, office and billing contacts</span></div></div>{ctx.portal_role==='admin'&&<button className="portal-secondary" onClick={()=>setEditor(null)}><Plus size={15}/>Add contact</button>}</div><div className="portal-contact-list">{contacts.map(c=><div className="portal-contact" key={c.id}><div className="portal-contact-type">{label(c.contact_type)}</div><div className="portal-contact-copy"><strong>{c.name}</strong>{c.title&&<span>{c.title}</span>}<div>{c.phone&&<a href={`tel:${c.phone}`}><Phone size={14}/>{c.phone}</a>}{c.email&&<a href={`mailto:${c.email}`}><Mail size={14}/>{c.email}</a>}</div></div>{ctx.portal_role==='admin'&&<div className="portal-contact-actions"><button onClick={()=>setEditor(c)}><Pencil size={15}/></button><button onClick={()=>void archive(c.id)}><Trash2 size={15}/></button></div>}</div>)}{!contacts.length&&<div className="portal-empty">No contacts have been added yet.</div>}</div></section></div></main>{editor!==undefined&&<PortalContactEditor customerId={ctx.customer_id} contact={editor} onClose={()=>setEditor(undefined)} onSaved={async()=>{setEditor(undefined);await load()}}/>}</div>
}

function PortalContactEditor({customerId,contact,onClose,onSaved}:{customerId:string;contact:Contact|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [f,setF]=useState({name:contact?.name||'',title:contact?.title||'',phone:contact?.phone||'',email:contact?.email||'',contact_type:contact?.contact_type||'field'}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await db.rpc('upsert_my_customer_contact',{_customer_id:customerId,_contact_id:contact?.id||null,_name:f.name.trim(),_title:f.title.trim(),_phone:f.phone.trim(),_email:f.email.trim(),_contact_type:f.contact_type});if(r.error)throw r.error;await onSaved()}catch(err){setError(readError(err))}finally{setBusy(false)}}
 return <div className="portal-modal-backdrop"><form className="portal-modal" onSubmit={save}><div className="portal-modal-head"><strong>{contact?'Edit contact':'Add contact'}</strong><button type="button" onClick={onClose}><X size={18}/></button></div>{error&&<div className="portal-message">{error}</div>}<label>Name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/></label><label>Role / title<input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Phone<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Contact type<select value={f.contact_type} onChange={e=>setF({...f,contact_type:e.target.value})}>{TYPES.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><div className="portal-modal-actions"><button type="button" className="portal-secondary" onClick={onClose}>Cancel</button><button className="portal-primary" disabled={busy}>{busy?'Saving…':'Save contact'}</button></div></form></div>
}
