import { useCallback, useEffect, useMemo, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { supabase } from './lib/supabase'
import './fleet-pack5.css'

const db=supabase as any
type Item={id:string;item_type:'labour'|'part'|'external';description:string;quantity:number;unit_cost_cents:number;amount_cents:number}
const money=(c:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100)
const dollarsToCents=(v:string)=>Math.round((Number(v)||0)*100)

export default function FleetWorkOrderItems({organizationId,workOrderId,disabled=false,onError,onChanged}:{organizationId:string;workOrderId:string;disabled?:boolean;onError:(message:string)=>void;onChanged?:()=>Promise<void>|void}){
 const [items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(false),[form,setForm]=useState({item_type:'part' as Item['item_type'],description:'',quantity:'1',unit_cost:''})
 const load=useCallback(async()=>{const r=await db.from('fleet_work_order_items').select('id,item_type,description,quantity,unit_cost_cents,amount_cents').eq('organization_id',organizationId).eq('work_order_id',workOrderId).order('created_at');if(r.error)onError(r.error.message);else setItems(r.data||[])},[organizationId,workOrderId,onError])
 useEffect(()=>{void load()},[load])
 const totals=useMemo(()=>({labour:items.filter(x=>x.item_type==='labour').reduce((s,x)=>s+x.amount_cents,0),parts:items.filter(x=>x.item_type==='part').reduce((s,x)=>s+x.amount_cents,0),external:items.filter(x=>x.item_type==='external').reduce((s,x)=>s+x.amount_cents,0)}),[items])
 const add=async(e:React.FormEvent)=>{e.preventDefault();if(disabled)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');const r=await db.from('fleet_work_order_items').insert({organization_id:organizationId,work_order_id:workOrderId,item_type:form.item_type,description:form.description.trim(),quantity:Number(form.quantity)||1,unit_cost_cents:dollarsToCents(form.unit_cost),created_by:u.user.id});if(r.error)throw r.error;setForm({item_type:'part',description:'',quantity:'1',unit_cost:''});await load();await onChanged?.()}catch(e:any){onError(e.message||String(e))}finally{setBusy(false)}}
 const remove=async(id:string)=>{if(disabled)return;setBusy(true);const r=await db.from('fleet_work_order_items').delete().eq('organization_id',organizationId).eq('id',id);if(r.error)onError(r.error.message);else{await load();await onChanged?.()}setBusy(false)}
 return <div className="pack5-items"><div className="pack5-items-head"><div><strong>Parts and labour</strong><span>Itemized costs automatically roll up to the work order and service history.</span></div><div><b>{money(totals.labour)}</b><small>labour</small><b>{money(totals.parts)}</b><small>parts</small><b>{money(totals.external)}</b><small>external</small></div></div><div className="pack5-item-list">{items.map(item=><div key={item.id}><span><strong>{item.description}</strong><small>{item.quantity} × {money(item.unit_cost_cents)} · {item.item_type}</small></span><b>{money(item.amount_cents)}</b>{!disabled&&<button type="button" onClick={()=>void remove(item.id)} disabled={busy} aria-label={'Delete '+item.description}><Trash2 size={14}/></button>}</div>)}{!items.length&&<div className="pack5-empty">No itemized costs yet.</div>}</div>{!disabled&&<form className="pack5-item-form" onSubmit={add}><select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value as Item['item_type']})}><option value="labour">Labour</option><option value="part">Part</option><option value="external">External</option></select><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" required/><input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} aria-label="Quantity"/><input type="number" min="0" step="0.01" value={form.unit_cost} onChange={e=>setForm({...form,unit_cost:e.target.value})} placeholder="$ each" aria-label="Unit cost"/><button disabled={busy}><Plus size={14}/>Add</button></form>}</div>
}