import { useCallback, useEffect, useState } from 'react'
import { Camera, Image, Trash2 } from 'lucide-react'
import { supabase } from './lib/supabase'
import './fleet-pack5.css'

const db=supabase as any
type Photo={id:string;name:string;storage_path:string;notes:string|null;created_at:string}
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||'photo'

export default function FleetPhotoPanel({organizationId,vehicleId,canEdit,onError}:{organizationId:string;vehicleId:string;canEdit:boolean;onError:(message:string)=>void}){
 const [photos,setPhotos]=useState<Photo[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[primary,setPrimaryPath]=useState<string|null>(null),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[notes,setNotes]=useState('')
 const load=useCallback(async()=>{const [r,v]=await Promise.all([db.from('fleet_documents').select('id,name,storage_path,notes,created_at').eq('organization_id',organizationId).eq('vehicle_id',vehicleId).eq('document_type','photo').order('created_at',{ascending:false}),db.from('fleet_vehicles').select('primary_photo_path').eq('organization_id',organizationId).eq('id',vehicleId).single()]);if(r.error){onError(r.error.message);return}if(!v.error)setPrimaryPath(v.data?.primary_photo_path||null);setPhotos(r.data||[]);const next:Record<string,string>={};for(const row of r.data||[]){const s=await supabase.storage.from('fleet-documents').createSignedUrl(row.storage_path,300);if(!s.error)next[row.id]=s.data.signedUrl}setUrls(next)},[organizationId,vehicleId,onError])
 useEffect(()=>{void load()},[load])
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file||!canEdit)return;setBusy(true);let path='';try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');path=organizationId+'/'+vehicleId+'/'+crypto.randomUUID()+'-'+safe(file.name);const up=await supabase.storage.from('fleet-documents').upload(path,file,{contentType:file.type||undefined});if(up.error)throw up.error;const meta=await db.from('fleet_documents').insert({organization_id:organizationId,vehicle_id:vehicleId,document_type:'photo',name:file.name,storage_path:path,mime_type:file.type||null,file_size:file.size,notes:notes.trim()||null,created_by:u.user.id}).select('id').single();if(meta.error){await supabase.storage.from('fleet-documents').remove([path]);throw meta.error}const current=await db.from('fleet_vehicles').select('primary_photo_path').eq('organization_id',organizationId).eq('id',vehicleId).single();if(!current.error&&!current.data?.primary_photo_path){const p=await db.from('fleet_vehicles').update({primary_photo_path:path}).eq('organization_id',organizationId).eq('id',vehicleId);if(p.error)throw p.error}setFile(null);setNotes('');await load()}catch(e:any){onError(e.message||String(e))}finally{setBusy(false)}}
 const setPrimary=async(path:string)=>{if(!canEdit)return;setBusy(true);const r=await db.from('fleet_vehicles').update({primary_photo_path:path}).eq('organization_id',organizationId).eq('id',vehicleId);if(r.error)onError(r.error.message);else setPrimaryPath(path);setBusy(false)}
 const remove=async(row:Photo)=>{if(!canEdit||!confirm('Delete this unit photo?'))return;setBusy(true);const v=await db.from('fleet_vehicles').select('primary_photo_path').eq('organization_id',organizationId).eq('id',vehicleId).single();if(!v.error&&v.data?.primary_photo_path===row.storage_path){const next=photos.find(p=>p.id!==row.id)?.storage_path||null;const u=await db.from('fleet_vehicles').update({primary_photo_path:next}).eq('organization_id',organizationId).eq('id',vehicleId);if(u.error){onError(u.error.message);setBusy(false);return}}const s=await supabase.storage.from('fleet-documents').remove([row.storage_path]);if(s.error){onError(s.error.message);setBusy(false);return}const r=await db.from('fleet_documents').delete().eq('organization_id',organizationId).eq('id',row.id);if(r.error)onError(r.error.message);else await load();setBusy(false)}
 return <section className="pack5-photo-panel"><div className="pack5-section-heading"><div><strong>Unit photos</strong><span>Keep current reference photos with the unit record.</span></div><Camera size={18}/></div><div className="pack5-photo-grid">{photos.map(row=><article key={row.id}>{urls[row.id]?<img src={urls[row.id]} alt={row.notes||row.name}/>:<div className="pack5-photo-placeholder"><Image size={24}/></div>}<div><strong>{row.notes||row.name}{primary===row.storage_path?' · Primary':''}</strong><small>{new Date(row.created_at).toLocaleDateString('en-CA')}</small></div>{canEdit&&<footer><button type="button" onClick={()=>void setPrimary(row.storage_path)} disabled={busy||primary===row.storage_path}>{primary===row.storage_path?'Primary':'Set primary'}</button><button type="button" onClick={()=>void remove(row)} disabled={busy} aria-label={'Delete '+row.name}><Trash2 size={14}/></button></footer>}</article>)}{!photos.length&&<div className="pack5-empty">No unit photos yet.</div>}</div>{canEdit&&<form className="pack5-photo-upload" onSubmit={upload}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} required/><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Photo note"/><button disabled={busy||!file}><Camera size={14}/>Upload photo</button></form>}</section>
}