import { useCallback, useEffect, useState } from 'react'
import { FileText, MapPin, Plus, Save, Trash2, Upload, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import './pack3-client-resources.css'

const db=supabase as any
type Contact={id:string;name:string;title:string|null}
type Site={id:string;name:string;address:string|null;access_directions:string|null;contact_id:string|null;purchase_order:string|null;afe_number:string|null;status:string}
type Doc={id:string;file_name:string;storage_path:string;file_size:number|null;category:string;description:string|null;visible_to_client:boolean;created_at:string}
type Profile={billing_address:string;default_purchase_order:string;default_afe_number:string;payment_terms:string;internal_notes:string;portal_notes:string}
const EMPTY:Profile={billing_address:'',default_purchase_order:'',default_afe_number:'',payment_terms:'',internal_notes:'',portal_notes:''}
const err=(e:unknown)=>e instanceof Error?e.message:String((e as any)?.message||e||'Something went wrong.')
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||'document'
const size=(v:number|null)=>v==null?'':v<1024?v+' B':v<1048576?(v/1024).toFixed(1)+' KB':(v/1048576).toFixed(1)+' MB'

export default function ManagerCustomerResources({organizationId,customerId,customerName,contacts}:{organizationId:string;customerId:string;customerName:string;contacts:Contact[]}){
 const [profile,setProfile]=useState<Profile>(EMPTY),[sites,setSites]=useState<Site[]>([]),[docs,setDocs]=useState<Doc[]>([]),[history,setHistory]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[siteOpen,setSiteOpen]=useState(false)
 const [site,setSite]=useState({id:'',name:'',address:'',access_directions:'',contact_id:'',purchase_order:'',afe_number:''})
 const [upload,setUpload]=useState({file:null as File|null,category:'general',description:'',visible_to_client:true})

 const load=useCallback(async()=>{
  const [c,s,d,j,t,i]=await Promise.all([
   db.from('customers').select('billing_address,default_purchase_order,default_afe_number,payment_terms,internal_notes,portal_notes').eq('organization_id',organizationId).eq('id',customerId).single(),
   db.from('customer_sites').select('id,name,address,access_directions,contact_id,purchase_order,afe_number,status').eq('organization_id',organizationId).eq('customer_id',customerId).order('name'),
   db.from('customer_documents').select('id,file_name,storage_path,file_size,category,description,visible_to_client,created_at').eq('organization_id',organizationId).eq('customer_id',customerId).order('created_at',{ascending:false}),
   db.from('jobs').select('id,job_number,title,status,created_at,completed_at').eq('organization_id',organizationId).eq('customer_id',customerId).order('created_at',{ascending:false}).limit(8),
   db.from('field_tickets').select('id,ticket_number,status,work_date').eq('organization_id',organizationId).eq('customer_id',customerId).order('work_date',{ascending:false}).limit(8),
   db.from('invoices').select('id,invoice_number,status,invoice_date,total').eq('organization_id',organizationId).eq('customer_id',customerId).order('invoice_date',{ascending:false}).limit(8),
  ])
  const bad=[c,s,d,j,t,i].find(x=>x.error)?.error;if(bad){setMessage(bad.message);return}
  setProfile({billing_address:c.data?.billing_address||'',default_purchase_order:c.data?.default_purchase_order||'',default_afe_number:c.data?.default_afe_number||'',payment_terms:c.data?.payment_terms||'',internal_notes:c.data?.internal_notes||'',portal_notes:c.data?.portal_notes||''})
  setSites(s.data||[]);setDocs(d.data||[])
  const rows=[
   ...(j.data||[]).map((x:any)=>({id:'j'+x.id,label:'Job '+x.job_number,detail:x.title+' · '+x.status,date:x.completed_at||x.created_at})),
   ...(t.data||[]).map((x:any)=>({id:'t'+x.id,label:'Ticket '+(x.ticket_number||'Draft'),detail:x.status,date:x.work_date})),
   ...(i.data||[]).map((x:any)=>({id:'i'+x.id,label:'Invoice '+x.invoice_number,detail:x.status+' · $'+Number(x.total||0).toFixed(2),date:x.invoice_date})),
  ].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,10)
  setHistory(rows)
 },[customerId,organizationId])
 useEffect(()=>{void load()},[load])

 const saveProfile=async()=>{setBusy(true);setMessage('');const r=await db.from('customers').update({billing_address:profile.billing_address.trim()||null,default_purchase_order:profile.default_purchase_order.trim()||null,default_afe_number:profile.default_afe_number.trim()||null,payment_terms:profile.payment_terms.trim()||null,internal_notes:profile.internal_notes.trim()||null,portal_notes:profile.portal_notes.trim()||null}).eq('organization_id',organizationId).eq('id',customerId);setMessage(r.error?r.error.message:'Client billing and notes saved.');setBusy(false)}
 const editSite=(row?:Site)=>{setSite(row?{id:row.id,name:row.name,address:row.address||'',access_directions:row.access_directions||'',contact_id:row.contact_id||'',purchase_order:row.purchase_order||'',afe_number:row.afe_number||''}:{id:'',name:'',address:'',access_directions:'',contact_id:'',purchase_order:'',afe_number:''});setSiteOpen(true)}
 const saveSite=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');const payload={organization_id:organizationId,customer_id:customerId,name:site.name.trim(),address:site.address.trim()||null,access_directions:site.access_directions.trim()||null,contact_id:site.contact_id||null,purchase_order:site.purchase_order.trim()||null,afe_number:site.afe_number.trim()||null,status:'active'};const r=site.id?await db.from('customer_sites').update(payload).eq('id',site.id).eq('organization_id',organizationId).eq('customer_id',customerId):await db.from('customer_sites').insert({...payload,created_by:u.user.id});if(r.error)throw r.error;setSiteOpen(false);await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 const archiveSite=async(id:string)=>{if(!confirm('Archive this site?'))return;const r=await db.from('customer_sites').update({status:'archived'}).eq('id',id).eq('organization_id',organizationId).eq('customer_id',customerId);if(r.error)setMessage(r.error.message);else await load()}
 const uploadDoc=async(e:React.FormEvent)=>{e.preventDefault();if(!upload.file)return;setBusy(true);let path='';try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');path=organizationId+'/'+customerId+'/'+crypto.randomUUID()+'-'+safe(upload.file.name);const up=await supabase.storage.from('customer-documents').upload(path,upload.file,{contentType:upload.file.type||undefined});if(up.error)throw up.error;const meta=await db.from('customer_documents').insert({organization_id:organizationId,customer_id:customerId,file_name:upload.file.name,storage_path:path,mime_type:upload.file.type||null,file_size:upload.file.size,category:upload.category,description:upload.description.trim()||null,visible_to_client:upload.visible_to_client,created_by:u.user.id});if(meta.error){await supabase.storage.from('customer-documents').remove([path]);throw meta.error}setUpload({file:null,category:'general',description:'',visible_to_client:true});setMessage('Document uploaded.');await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 const openDoc=async(row:Doc)=>{const r=await supabase.storage.from('customer-documents').createSignedUrl(row.storage_path,120);if(r.error)setMessage(r.error.message);else window.open(r.data.signedUrl,'_blank','noopener,noreferrer')}
 const deleteDoc=async(row:Doc)=>{if(!confirm('Delete this document?'))return;setBusy(true);const s=await supabase.storage.from('customer-documents').remove([row.storage_path]);if(s.error){setMessage(s.error.message);setBusy(false);return}const r=await db.from('customer_documents').delete().eq('id',row.id).eq('organization_id',organizationId);if(r.error)setMessage(r.error.message);else await load();setBusy(false)}

 return <div className="pack3-manager-resources">
  {message&&<div className="pack3-message">{message}</div>}
  <section className="client-section pack3-profile-section"><div className="client-section-title"><strong>Billing, references and notes</strong><span>Internal notes stay private. Client portal notes are visible to the client.</span></div><div className="pack3-grid two"><label>Billing address<textarea value={profile.billing_address} onChange={e=>setProfile({...profile,billing_address:e.target.value})}/></label><label>Payment terms<input value={profile.payment_terms} onChange={e=>setProfile({...profile,payment_terms:e.target.value})} placeholder="Net 30"/></label><label>Default PO<input value={profile.default_purchase_order} onChange={e=>setProfile({...profile,default_purchase_order:e.target.value})}/></label><label>Default AFE<input value={profile.default_afe_number} onChange={e=>setProfile({...profile,default_afe_number:e.target.value})}/></label></div><label>Internal notes <small>Northborn staff only</small><textarea value={profile.internal_notes} onChange={e=>setProfile({...profile,internal_notes:e.target.value})}/></label><label>Client portal notes <small>Visible to this client</small><textarea value={profile.portal_notes} onChange={e=>setProfile({...profile,portal_notes:e.target.value})}/></label><button className="client-primary" onClick={()=>void saveProfile()} disabled={busy}><Save size={15}/>Save billing and notes</button></section>
  <section className="client-section"><div className="client-section-title row"><div><strong>Sites and locations</strong><span>Reusable locations, access directions, contacts and PO/AFE defaults</span></div><button className="client-secondary" onClick={()=>editSite()}><Plus size={15}/>Add site</button></div><div className="pack3-site-list">{sites.filter(x=>x.status==='active').map(row=><button type="button" className="pack3-site-row" key={row.id} onClick={()=>editSite(row)}><MapPin size={17}/><span><strong>{row.name}</strong><small>{row.address||'No address'}{row.purchase_order?' · PO '+row.purchase_order:''}{row.afe_number?' · AFE '+row.afe_number:''}</small></span></button>)}{!sites.some(x=>x.status==='active')&&<div className="client-empty">No reusable sites yet.</div>}</div></section>
  <section className="client-section"><div className="client-section-title"><strong>Documents</strong><span>Private customer files. Choose which documents are visible in the client portal.</span></div><form className="pack3-upload" onSubmit={uploadDoc}><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.csv,.docx,.xlsx" onChange={e=>setUpload({...upload,file:e.target.files?.[0]||null})} required/><select value={upload.category} onChange={e=>setUpload({...upload,category:e.target.value})}><option value="general">General</option><option value="agreement">Agreement</option><option value="insurance">Insurance</option><option value="po_afe">PO / AFE</option><option value="site">Site</option><option value="safety">Safety</option><option value="other">Other</option></select><input value={upload.description} onChange={e=>setUpload({...upload,description:e.target.value})} placeholder="Description"/><label className="pack3-check"><input type="checkbox" checked={upload.visible_to_client} onChange={e=>setUpload({...upload,visible_to_client:e.target.checked})}/>Visible to client</label><button className="client-primary" disabled={busy||!upload.file}><Upload size={15}/>Upload</button></form><div className="pack3-document-list">{docs.map(row=><div className="pack3-document-row" key={row.id}><FileText size={17}/><button type="button" onClick={()=>void openDoc(row)}><strong>{row.file_name}</strong><small>{row.category.replaceAll('_',' ')}{row.file_size?' · '+size(row.file_size):''}{row.visible_to_client?' · Client visible':' · Internal only'}</small></button><label className="pack3-check compact"><input type="checkbox" checked={row.visible_to_client} onChange={async e=>{const r=await db.from('customer_documents').update({visible_to_client:e.target.checked}).eq('id',row.id).eq('organization_id',organizationId);if(r.error)setMessage(r.error.message);else await load()}}/>Portal</label><button className="pack3-icon danger" onClick={()=>void deleteDoc(row)}><Trash2 size={15}/></button></div>)}{!docs.length&&<div className="client-empty">No customer documents yet.</div>}</div></section>
  <section className="client-section"><div className="client-section-title"><strong>Customer history</strong><span>Recent jobs, tickets and invoices for {customerName}</span></div><div className="pack3-history-list">{history.map(row=><div key={row.id}><span><strong>{row.label}</strong><small>{row.detail}</small></span><time>{row.date?new Date(row.date).toLocaleDateString('en-CA'):''}</time></div>)}{!history.length&&<div className="client-empty">No history yet.</div>}</div></section>
  {siteOpen&&<div className="portal-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSiteOpen(false)}}><form className="portal-modal" onSubmit={saveSite}><div className="portal-modal-head"><strong>{site.id?'Edit site':'Add site'}</strong><button type="button" onClick={()=>setSiteOpen(false)}><X size={18}/></button></div><label>Site name<input value={site.name} onChange={e=>setSite({...site,name:e.target.value})} required/></label><label>Address<input value={site.address} onChange={e=>setSite({...site,address:e.target.value})}/></label><label>Access directions<textarea value={site.access_directions} onChange={e=>setSite({...site,access_directions:e.target.value})}/></label><label>Primary contact<select value={site.contact_id} onChange={e=>setSite({...site,contact_id:e.target.value})}><option value="">No contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}{c.title?' · '+c.title:''}</option>)}</select></label><div className="pack3-grid two"><label>PO<input value={site.purchase_order} onChange={e=>setSite({...site,purchase_order:e.target.value})}/></label><label>AFE<input value={site.afe_number} onChange={e=>setSite({...site,afe_number:e.target.value})}/></label></div><div className="portal-modal-actions">{site.id&&<button type="button" className="pack3-danger-button" onClick={()=>{void archiveSite(site.id);setSiteOpen(false)}}>Archive</button>}<button type="button" className="portal-secondary" onClick={()=>setSiteOpen(false)}>Cancel</button><button className="portal-primary" disabled={busy}>Save site</button></div></form></div>}
 </div>
}
