import { useCallback, useEffect, useMemo, useState } from 'react'
import { NavLink, useSearchParams } from 'react-router-dom'
import { BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight, ContactRound, Copy, Gauge, HardHat, Plus, ReceiptText, Repeat2, Search, ShieldCheck, Truck, Users, Wrench, X } from 'lucide-react'
import NorthbornDateTimePicker from './NorthbornDateTimePicker'
import ManagerJobRequestsPanel from './ManagerJobRequestsPanel'
import RoleAwareApp from './RoleAwareApp'
import { supabase } from './lib/supabase'
import { resolveWorkspaceAccess } from './workspace-access'
import { dispatchStageLabel, statusLabel } from './job-operations'
import './manager-jobs.css'
import './manager-jobs-history.css'

const db=supabase as any
type Organization={id:string;name:string}
type Customer={id:string;name:string}
type Job={id:string;customer_id:string;job_number:string;title:string;site_name:string|null;site_address:string|null;shop_time:string|null;onsite_time:string|null;scheduled_start:string|null;scheduled_end:string|null;status:string;dispatch_stage:string;notes:string|null;completed_at:string|null;completed_by:string|null;recurrence_series_id:string|null;recurrence_rule:string|null;recurrence_parent_id:string|null}
const NAV=[['Dashboard','/',Gauge],['Calendar','/calendar',CalendarDays],['Dispatch','/dispatch',CalendarDays],['Jobs','/jobs',BriefcaseBusiness],['Customers','/customers',ContactRound],['Employees','/employees',Users],['Fleet','/fleet',Truck],['Maintenance','/maintenance',Wrench],['Safety','/safety',ShieldCheck],['Timesheets','/timesheets',HardHat],['Invoices','/invoices',ReceiptText]] as const
const readError=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message||e||'Something went wrong.')
const toIso=(value:string)=>value?new Date(value).toISOString():null
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat('en-CA',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value)):'Not set'
const jobTime=(job:Job)=>job.onsite_time||job.scheduled_start||job.shop_time
const recurrenceLabel=(value:string|null)=>value?({daily:'Daily',weekly:'Weekly',biweekly:'Every 2 weeks',monthly:'Monthly'} as Record<string,string>)[value]||statusLabel(value):null

export default function ManagerJobsPage(){
  const [organization,setOrganization]=useState<Organization|null>(null),[roleKey,setRoleKey]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[query,setQuery]=useState('')
  const [params,setParams]=useSearchParams()
  const view=(params.get('view')||'active') as 'active'|'completed'|'cancelled'
  const load=useCallback(async()=>{setError('');try{const {data:s,error:se}=await supabase.auth.getSession();if(se)throw se;const user=s.session?.user;if(!user){setLoading(false);return}const access=await resolveWorkspaceAccess(user.id);if(access.kind!=='internal'){setLoading(false);return}setRoleKey(access.roleKey);if(access.roleKey==='operator'){setLoading(false);return}const org={id:access.organizationId,name:access.organizationName};setOrganization(org);const [c,j]=await Promise.all([db.from('customers').select('id,name').eq('organization_id',org.id).neq('status','archived').order('name'),db.from('jobs').select('id,customer_id,job_number,title,site_name,site_address,shop_time,onsite_time,scheduled_start,scheduled_end,status,dispatch_stage,notes,completed_at,completed_by,recurrence_series_id,recurrence_rule,recurrence_parent_id').eq('organization_id',org.id).order('updated_at',{ascending:false})]);const er=c.error||j.error;if(er)setError(er.message);setCustomers(c.data||[]);setJobs(j.data||[])}catch(e){setError(readError(e))}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const groups=useMemo(()=>({
    active:jobs.filter(j=>!['completed','cancelled'].includes(j.status)).sort((a,b)=>String(jobTime(a)||'').localeCompare(String(jobTime(b)||''))),
    completed:jobs.filter(j=>j.status==='completed').sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||''))),
    cancelled:jobs.filter(j=>j.status==='cancelled').sort((a,b)=>String(b.onsite_time||b.scheduled_start||'').localeCompare(String(a.onsite_time||a.scheduled_start||''))),
  }),[jobs])
  const shown=useMemo(()=>{const term=query.trim().toLowerCase();const list=groups[view]||groups.active;if(!term)return list;return list.filter(j=>{const customer=customers.find(c=>c.id===j.customer_id)?.name||'';return [j.job_number,j.title,j.site_name,j.site_address,customer,statusLabel(j.status),dispatchStageLabel(j.dispatch_stage)].some(v=>String(v||'').toLowerCase().includes(term))})},[groups,view,query,customers])
  const changeView=(next:'active'|'completed'|'cancelled')=>{const q=new URLSearchParams(params);if(next==='active')q.delete('view');else q.set('view',next);setParams(q,{replace:true})}
  const duplicate=async(job:Job)=>{if(!organization)return;setError('');try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');const stamp=new Date().toISOString().replace(/\D/g,'').slice(4,12);const r=await db.from('jobs').insert({organization_id:organization.id,customer_id:job.customer_id,job_number:job.job_number+'-COPY-'+stamp,title:job.title,site_name:job.site_name,site_address:job.site_address,status:'draft',dispatch_stage:'unassigned',notes:job.notes,recurrence_parent_id:job.id,recurrence_series_id:job.recurrence_series_id,recurrence_rule:job.recurrence_rule,created_by:u.user.id});if(r.error)throw r.error;await load()}catch(e){setError(readError(e))}}
  if(loading)return <div className="manager-jobs-loading">Loading jobs…</div>
  if(!organization||roleKey==='operator')return <RoleAwareApp/>
  return <div className="manager-jobs-shell"><aside className="manager-jobs-sidebar"><div className="manager-jobs-brand"><div>N</div><span><strong>NORTHBORN</strong><small>{organization.name}</small></span></div><nav>{NAV.map(([n,p,I])=><NavLink key={p} to={p} end={p==='/' }><I size={18}/><span>{n}</span></NavLink>)}</nav></aside><main className="manager-jobs-main"><header className="manager-jobs-header"><div><span className="manager-jobs-eyebrow">OPERATIONS</span><strong>Jobs</strong></div><button className="manager-jobs-primary" onClick={()=>setOpen(true)} disabled={!customers.length}><Plus size={17}/>New job</button></header>
    <section className="manager-jobs-page"><div className="manager-jobs-hero"><span className="manager-jobs-eyebrow">WORK PIPELINE</span><h1>Jobs from draft to done.</h1><p>Create one-off or recurring work, find it quickly, then send active jobs to Dispatch for crew, equipment and field progress.</p></div>
      {error&&<div className="manager-jobs-message">{error}</div>}
      {!customers.length&&<div className="manager-jobs-notice">Add a client before creating a job. <NavLink to="/customers">Open Clients</NavLink></div>}
      {view==='active'&&<ManagerJobRequestsPanel organizationId={organization.id} onChanged={()=>load()}/>}
      <div className="manager-job-toolbar"><div className="manager-job-tabs"><button type="button" className={view==='active'?'active':''} onClick={()=>changeView('active')}><BriefcaseBusiness size={16}/>Active <span>{groups.active.length}</span></button><button type="button" className={view==='completed'?'active completed':''} onClick={()=>changeView('completed')}><CheckCircle2 size={16}/>Completed <span>{groups.completed.length}</span></button><button type="button" className={view==='cancelled'?'active cancelled':''} onClick={()=>changeView('cancelled')}><X size={16}/>Cancelled <span>{groups.cancelled.length}</span></button></div><label className="manager-job-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search jobs, client, site or status"/></label></div>
      <div className="manager-jobs-list">{shown.map(job=>{const client=customers.find(c=>c.id===job.customer_id),repeat=recurrenceLabel(job.recurrence_rule);return <article className={'manager-job-card'+(view==='completed'?' manager-job-card-completed':'')} key={job.id}><NavLink to={'/dispatch?job='+job.id} className="manager-job-card-link"><div><span className="manager-job-number">{job.job_number}</span><h2>{job.title}</h2><p>{client?.name||'Unknown client'} · {job.site_name||job.site_address||'Site not set'}</p>{repeat&&<small className="manager-job-repeat"><Repeat2 size={13}/>{repeat}</small>}</div><div className="manager-job-times">{view==='completed'?<><span><b>Completed</b>{fmt(job.completed_at)}</span><span><b>On site</b>{fmt(job.onsite_time||job.scheduled_start)}</span></>:<><span><b>Shop</b>{fmt(job.shop_time)}</span><span><b>On site</b>{fmt(job.onsite_time||job.scheduled_start)}</span></>}</div><div className="manager-job-state"><span className={'manager-job-status status-'+job.status}>{statusLabel(job.status)}</span><small>{dispatchStageLabel(job.dispatch_stage)}</small></div><ChevronRight size={19}/></NavLink><button className="manager-job-copy" type="button" onClick={()=>void duplicate(job)} title="Duplicate job"><Copy size={16}/><span>Duplicate</span></button></article>})}{!shown.length&&<div className="manager-jobs-empty">No jobs match this view.</div>}</div>
    </section></main>
    {open&&<NewJobModal organization={organization} customers={customers} onClose={()=>setOpen(false)} onCreated={async()=>{setOpen(false);await load()}}/>}
  </div>
}

function NewJobModal({organization,customers,onClose,onCreated}:{organization:Organization;customers:Customer[];onClose:()=>void;onCreated:()=>Promise<void>}){
  const [form,setForm]=useState({customer_id:customers[0]?.id||'',job_number:'',title:'',site_name:'',site_address:'',shop_time:'',onsite_time:'',scheduled_end:'',notes:'',status:'scheduled',recurrence:'none',occurrences:'4'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newClientOpen,setNewClientOpen]=useState(false),[clientForm,setClientForm]=useState({name:'',phone:'',billing_email:'',address:''}),[customerOptions,setCustomerOptions]=useState(customers.slice())
  const createClient=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');const r=await db.from('customers').insert({organization_id:organization.id,name:clientForm.name.trim(),phone:clientForm.phone.trim()||null,billing_email:clientForm.billing_email.trim().toLowerCase()||null,address:clientForm.address.trim()||null,status:'active',created_by:u.user.id}).select('id,name').single();if(r.error)throw r.error;setCustomerOptions(options=>[...options,r.data].sort((a,b)=>a.name.localeCompare(b.name)));setForm(current=>({...current,customer_id:r.data.id}));setNewClientOpen(false);setClientForm({name:'',phone:'',billing_email:'',address:''})}catch(err){setError(readError(err))}finally{setBusy(false)}}
  const recurrenceDate=(base:string,index:number,rule:string)=>{if(!base)return null;const d=new Date(base);if(rule==='daily')d.setDate(d.getDate()+index);if(rule==='weekly')d.setDate(d.getDate()+7*index);if(rule==='biweekly')d.setDate(d.getDate()+14*index);if(rule==='monthly')d.setMonth(d.getMonth()+index);return d.toISOString()}
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error('Sign in required');if(!form.customer_id)throw new Error('Choose a client.');if(!form.title.trim())throw new Error('Enter a job title.');const count=form.recurrence==='none'?1:Math.max(2,Math.min(Number(form.occurrences)||2,52));const series=form.recurrence==='none'?null:crypto.randomUUID();const baseOnsite=toIso(form.onsite_time),baseShop=toIso(form.shop_time),baseEnd=toIso(form.scheduled_end);const stamp=new Date().toISOString().replace(/\D/g,'').slice(2,12);const rootNumber=form.job_number.trim()||('JOB-'+stamp);const rows=Array.from({length:count},(_,index)=>({organization_id:organization.id,customer_id:form.customer_id,job_number:index===0?rootNumber:rootNumber+'-'+String(index+1).padStart(2,'0'),title:form.title.trim(),site_name:form.site_name.trim()||null,site_address:form.site_address.trim()||null,shop_time:form.recurrence==='none'?baseShop:recurrenceDate(baseShop||'',index,form.recurrence),onsite_time:form.recurrence==='none'?baseOnsite:recurrenceDate(baseOnsite||'',index,form.recurrence),scheduled_start:form.recurrence==='none'?baseOnsite:recurrenceDate(baseOnsite||'',index,form.recurrence),scheduled_end:form.recurrence==='none'?baseEnd:recurrenceDate(baseEnd||'',index,form.recurrence),notes:form.notes.trim()||null,status:form.status,dispatch_stage:'unassigned',recurrence_series_id:series,recurrence_rule:form.recurrence==='none'?null:form.recurrence,created_by:u.user.id}));const r=await db.from('jobs').insert(rows);if(r.error)throw r.error;await onCreated()}catch(err){setError(readError(err))}finally{setBusy(false)}}
  return <div className="manager-job-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="manager-job-modal"><div className="manager-job-modal-head"><div><span className="manager-jobs-eyebrow">NEW JOB</span><h2>Create scheduled work</h2></div><button onClick={onClose}><X size={20}/></button></div>{error&&<div className="manager-jobs-message">{error}</div>}<form onSubmit={save} className="manager-job-form"><div className="manager-job-form-grid">
    <label><span>Client</span><div className="manager-client-inline"><select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} required>{customerOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" onClick={()=>setNewClientOpen(v=>!v)} aria-label="Quick add client"><Plus size={16}/></button></div></label>
    <label><span>Job number</span><input value={form.job_number} onChange={e=>setForm({...form,job_number:e.target.value})} placeholder="Auto if blank"/></label>
    <label className="wide"><span>Job title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label>
    <label><span>Site name</span><input value={form.site_name} onChange={e=>setForm({...form,site_name:e.target.value})}/></label><label><span>Site address</span><input value={form.site_address} onChange={e=>setForm({...form,site_address:e.target.value})}/></label>
    <label><span>Lifecycle state</span><select aria-label="Lifecycle state" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></label>
    <label><span>Repeat</span><select aria-label="Repeat" value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}><option value="none">One-time job</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="biweekly">Every 2 weeks</option><option value="monthly">Monthly</option></select></label>
    {form.recurrence!=='none'&&<label><span>Occurrences</span><input aria-label="Occurrences" type="number" min="2" max="52" value={form.occurrences} onChange={e=>setForm({...form,occurrences:e.target.value})}/></label>}
    <label><span>Be at shop</span><NorthbornDateTimePicker value={form.shop_time} onChange={value=>setForm({...form,shop_time:value})} placeholder="Choose shop time"/></label><label><span>On site</span><NorthbornDateTimePicker value={form.onsite_time} onChange={value=>setForm({...form,onsite_time:value})} placeholder="Choose on-site time"/></label><label><span>Expected finish</span><NorthbornDateTimePicker value={form.scheduled_end} onChange={value=>setForm({...form,scheduled_end:value})} min={form.onsite_time} placeholder="Choose finish time"/></label>
    <label className="wide"><span>Notes</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="manager-job-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="manager-jobs-primary" disabled={busy}>{busy?'Creating…':form.recurrence==='none'?'Create job':'Create series'}</button></div></form>
    {newClientOpen&&<form className="manager-quick-client" onSubmit={createClient}><strong>Quick add client</strong><div><input placeholder="Company name" value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})} required/><input placeholder="Main phone" value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/><input type="email" placeholder="Billing email" value={clientForm.billing_email} onChange={e=>setClientForm({...clientForm,billing_email:e.target.value})}/><input placeholder="Address" value={clientForm.address} onChange={e=>setClientForm({...clientForm,address:e.target.value})}/></div><button className="manager-jobs-primary" disabled={busy}>Add client</button></form>}
  </section></div>
}
