import { useCallback, useEffect, useState } from 'react'
import { ShieldCheck, Trash2, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import './team-member-access-manager.css'
const db=supabase as any
const MANAGEABLE=['operator','dispatcher','supervisor','mechanic','safety','accounting','admin'] as const
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export default function TeamMemberAccessManager({organizationId,memberId,userId,name,isSelf,onClose,onSaved,onError}:{organizationId:string;memberId:string;userId:string;name:string;isSelf:boolean;onClose:()=>void;onSaved:()=>Promise<void>;onError:(v:string)=>void}){
 const [roles,setRoles]=useState<Map<string,string>>(new Map()),[assigned,setAssigned]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const [r,m]=await Promise.all([db.from('roles').select('id,key').is('organization_id',null).in('key',[...MANAGEABLE,'owner']),db.from('membership_roles').select('role_id,role:roles(key)').eq('membership_id',memberId)]);const bad=r.error||m.error;if(bad){onError(bad.message);return}setRoles(new Map((r.data||[]).map((x:any)=>[x.key,x.id])));setAssigned(new Set((m.data||[]).map((x:any)=>x.role?.key).filter(Boolean)))},[memberId,onError])
 useEffect(()=>{void load()},[load])
 const isOwner=assigned.has('owner')
 const toggle=async(key:string)=>{if(isOwner||key==='owner')return;setBusy(true);try{const roleId=roles.get(key);if(!roleId)throw new Error('Role unavailable');const r=assigned.has(key)?await db.from('membership_roles').delete().eq('membership_id',memberId).eq('role_id',roleId):await db.from('membership_roles').insert({membership_id:memberId,role_id:roleId});if(r.error)throw r.error;await load();await onSaved()}catch(e:any){onError(e.message||String(e))}finally{setBusy(false)}}
 const remove=async()=>{if(isSelf||isOwner||!confirm('Remove this person from Northborn? Their employee record will be archived when one is linked.'))return;setBusy(true);try{const m=await db.from('organization_members').update({status:'removed'}).eq('id',memberId).eq('organization_id',organizationId);if(m.error)throw m.error;const e=await db.from('employees').update({status:'archived'}).eq('organization_id',organizationId).eq('user_id',userId);if(e.error)throw e.error;await onSaved();onClose()}catch(e:any){onError(e.message||String(e))}finally{setBusy(false)}}
 return <div className="tma-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="tma-card"><header><div><span>TEAM ACCESS</span><h2>{name}</h2></div><button onClick={onClose}><X size={19}/></button></header><div className="tma-note"><ShieldCheck size={18}/><span>{isOwner?'Owner access is protected.':isSelf?'You can review your roles here, but you cannot remove your own account.':'Assign one or more roles. Access is the union of every selected role.'}</span></div><div className="tma-roles">{isOwner&&<label className="locked"><span><strong>Owner</strong><small>Protected ownership role</small></span><input type="checkbox" checked readOnly/></label>}{MANAGEABLE.map(k=><label key={k}><span><strong>{label(k)}</strong><small>{k==='admin'?'Company administration':k==='operator'?'Assigned field work and self service':label(k)+' module access'}</small></span><input type="checkbox" checked={assigned.has(k)} disabled={busy||isOwner} onChange={()=>void toggle(k)}/></label>)}</div>{!isOwner&&!isSelf&&<button className="tma-remove" disabled={busy} onClick={()=>void remove()}><Trash2 size={16}/>Remove company access</button>}</section></div>
}