-- Mallard Environmental starter classification library.
-- Keeps existing user-created classifications unchanged and allocates only permanently unused codes.
-- The catalog is based on common Alberta oilfield waste streams and environmental sampling matrices
-- including AER waste-management guidance and common municipal/industrial environmental matrices.

do $$
declare
  r record;
begin
  for r in
    select *
    from (values
    ('Non Oilfield', 'Sumps & Wastewater', 'Vehicle Wash Water'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Car Wash Sludge'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Floor Drain Sump Water'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Floor Drain Sump Sludge'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Oil-Water Separator Water'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Oil-Water Separator Sludge'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Catch Basin Water'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Catch Basin Sediment'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Industrial Wastewater'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Sanitary Wastewater'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Lift Station Wastewater'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Grease Trap Waste'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Process Wastewater'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Rinse Water'),
    ('Non Oilfield', 'Sumps & Wastewater', 'Pressure Wash Water'),
    ('Non Oilfield', 'Wastewater & Septic', 'Septage'),
    ('Non Oilfield', 'Wastewater & Septic', 'Septic Tank Effluent'),
    ('Non Oilfield', 'Wastewater & Septic', 'Septic Tank Sludge'),
    ('Non Oilfield', 'Wastewater & Septic', 'Sewage Sludge'),
    ('Non Oilfield', 'Wastewater & Septic', 'Wastewater Lagoon Influent'),
    ('Non Oilfield', 'Wastewater & Septic', 'Wastewater Lagoon Effluent'),
    ('Non Oilfield', 'Wastewater & Septic', 'Wastewater Lagoon Sludge'),
    ('Non Oilfield', 'Wastewater & Septic', 'Biosolids'),
    ('Non Oilfield', 'Water & Dewatering', 'Stormwater'),
    ('Non Oilfield', 'Water & Dewatering', 'Construction Runoff'),
    ('Non Oilfield', 'Water & Dewatering', 'Dewatering Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Excavation Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Trench Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Contaminated Surface Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Groundwater'),
    ('Non Oilfield', 'Water & Dewatering', 'Monitoring Well Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Pond Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Ditch Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Creek / Stream Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Hydrotest Water'),
    ('Non Oilfield', 'Water & Dewatering', 'Firewater'),
    ('Non Oilfield', 'Water & Dewatering', 'Cooling Tower Blowdown'),
    ('Non Oilfield', 'Water & Dewatering', 'Boiler Blowdown'),
    ('Non Oilfield', 'Water & Dewatering', 'Landfill Leachate'),
    ('Non Oilfield', 'Water & Dewatering', 'Leachate-Impacted Water'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Hydrovac Slurry - Non-Impacted'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Clay Slurry'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Bentonite Slurry'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Directional Drilling Mud'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Directional Drilling Cuttings'),
    ('Non Oilfield', 'Hydrovac & Excavation', 'Wet Soil / Spoil'),
    ('Non Oilfield', 'Soil & Sediment', 'General Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Contaminated Soil - Unknown Source'),
    ('Non Oilfield', 'Soil & Sediment', 'Diesel-Impacted Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Gasoline-Impacted Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Used Oil-Impacted Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Glycol-Impacted Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Salt-Impacted Soil'),
    ('Non Oilfield', 'Soil & Sediment', 'Sediment'),
    ('Non Oilfield', 'Soil & Sediment', 'Dredged Sediment'),
    ('Non Oilfield', 'Soil & Sediment', 'Fill Material'),
    ('Non Oilfield', 'Soil & Sediment', 'Road Salt-Impacted Soil'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Landfill Wastewater'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Landfill Sump Water'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Landfill Sludge'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Mixed Non-Hazardous Waste'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Unknown Wastewater'),
    ('Non Oilfield', 'Landfill & Solid Waste', 'Unknown Sludge'),
    ('Non Oilfield', 'Agricultural & Organic', 'Manure Lagoon Liquid'),
    ('Non Oilfield', 'Agricultural & Organic', 'Manure Lagoon Sludge'),
    ('Oilfield', 'Production Fluids', 'Crude Oil'),
    ('Oilfield', 'Production Fluids', 'Condensate'),
    ('Oilfield', 'Production Fluids', 'Oilfield Emulsion'),
    ('Oilfield', 'Production Fluids', 'Oily Produced Water'),
    ('Oilfield', 'Production Fluids', 'Formation Water'),
    ('Oilfield', 'Production Fluids', 'Oilfield Brine'),
    ('Oilfield', 'Production Fluids', 'Sour Water'),
    ('Oilfield', 'Production Fluids', 'Separator Water'),
    ('Oilfield', 'Production Fluids', 'Treater Water'),
    ('Oilfield', 'Production Fluids', 'Skim Oil'),
    ('Oilfield', 'Production Fluids', 'Recovered Oil'),
    ('Oilfield', 'Production Fluids', 'BS&W / Basic Sediment and Water'),
    ('Oilfield', 'Tanks & Vessels', 'Tank Sludge'),
    ('Oilfield', 'Tanks & Vessels', 'Produced Water Tank Sediment'),
    ('Oilfield', 'Tanks & Vessels', 'Crude Oil Tank Wash Water'),
    ('Oilfield', 'Tanks & Vessels', 'Condensate Tank Wash Water'),
    ('Oilfield', 'Tanks & Vessels', 'Produced Water Tank Wash Water'),
    ('Oilfield', 'Tanks & Vessels', 'Frac Tank Residue'),
    ('Oilfield', 'Tanks & Vessels', 'Separator Sludge'),
    ('Oilfield', 'Tanks & Vessels', 'Treater Sludge'),
    ('Oilfield', 'Tanks & Vessels', 'Skim Tank Sludge'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Pigging Liquid'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Pigging Solids'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Flush Water'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Hydrocarbon Residual'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Emulsion'),
    ('Oilfield', 'Pipelines & Pigging', 'Pipeline Scale / Debris'),
    ('Oilfield', 'Pipelines & Pigging', 'Linefill / Displacement Fluid'),
    ('Oilfield', 'Drilling Waste', 'Water-Based Drilling Mud'),
    ('Oilfield', 'Drilling Waste', 'Oil-Based / Invert Drilling Mud'),
    ('Oilfield', 'Drilling Waste', 'Water-Based Drill Cuttings'),
    ('Oilfield', 'Drilling Waste', 'Oil-Based Drill Cuttings'),
    ('Oilfield', 'Drilling Waste', 'Drilling Sump Fluid'),
    ('Oilfield', 'Drilling Waste', 'Drilling Sump Sludge'),
    ('Oilfield', 'Drilling Waste', 'Drilling Rig Wash Water'),
    ('Oilfield', 'Drilling Waste', 'Mud Tank Residue'),
    ('Oilfield', 'Cementing & Completions', 'Cement Returns'),
    ('Oilfield', 'Cementing & Completions', 'Cement Slurry'),
    ('Oilfield', 'Cementing & Completions', 'Completion Fluid'),
    ('Oilfield', 'Cementing & Completions', 'Well Workover Fluid'),
    ('Oilfield', 'Cementing & Completions', 'Kill Fluid'),
    ('Oilfield', 'Cementing & Completions', 'Frac Flowback Water'),
    ('Oilfield', 'Cementing & Completions', 'Hydrocarbon-Based Frac Flowback'),
    ('Oilfield', 'Cementing & Completions', 'Spent Frac Fluid'),
    ('Oilfield', 'Cementing & Completions', 'Slickwater'),
    ('Oilfield', 'Cementing & Completions', 'Gelled Frac Water'),
    ('Oilfield', 'Cementing & Completions', 'Acid Returns'),
    ('Oilfield', 'Cementing & Completions', 'Spent Acid'),
    ('Oilfield', 'Hydrovac & Excavation', 'Hydrovac - Crude Oil / Condensate Impacted'),
    ('Oilfield', 'Hydrovac & Excavation', 'Hydrovac - Refined Fuel / Oil Impacted'),
    ('Oilfield', 'Hydrovac & Excavation', 'Hydrovac - Emulsion Impacted'),
    ('Oilfield', 'Hydrovac & Excavation', 'Hydrovac - Produced Water / Salt Impacted'),
    ('Oilfield', 'Hydrovac & Excavation', 'Hydrovac - Unknown Oilfield Impact'),
    ('Oilfield', 'Hydrovac & Excavation', 'Pipeline Daylighting Slurry'),
    ('Oilfield', 'Hydrovac & Excavation', 'Oilfield Excavation Water'),
    ('Oilfield', 'Hydrovac & Excavation', 'Oilfield Trench Water'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Crude Oil-Impacted Soil'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Condensate-Impacted Soil'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Emulsion-Impacted Soil'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Refined Fuel-Impacted Soil - Oilfield'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Produced Water / Salt-Impacted Soil'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Hydrocarbon-Impacted Groundwater'),
    ('Oilfield', 'Remediation & Spill Cleanup', 'Salt-Impacted Groundwater'),
    ('Oilfield', 'Facility Process Fluids', 'Compressor Scrubber Liquid'),
    ('Oilfield', 'Facility Process Fluids', 'Flare Knockout Liquid'),
    ('Oilfield', 'Facility Process Fluids', 'Dehydrator Glycol'),
    ('Oilfield', 'Facility Process Fluids', 'Amine Solution'),
    ('Oilfield', 'Facility Process Fluids', 'Methanol - Oilfield'),
    ('Oilfield', 'Facility Process Fluids', 'Spent H2S Scavenger Fluid'),
    ('Oilfield', 'Facility Process Fluids', 'Corrosion Inhibitor'),
    ('Other / Specialty', 'Petroleum Products', 'Gasoline'),
    ('Other / Specialty', 'Petroleum Products', 'Diesel Fuel'),
    ('Other / Specialty', 'Petroleum Products', 'Jet Fuel'),
    ('Other / Specialty', 'Petroleum Products', 'Kerosene'),
    ('Other / Specialty', 'Petroleum Products', 'Heating Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Waste Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Engine Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Hydraulic Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Gear Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Transmission Fluid'),
    ('Other / Specialty', 'Petroleum Products', 'Mineral Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Transformer Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Cutting Oil'),
    ('Other / Specialty', 'Petroleum Products', 'Lubricating Oil'),
    ('Other / Specialty', 'Glycols & Coolants', 'Ethylene Glycol'),
    ('Other / Specialty', 'Glycols & Coolants', 'Propylene Glycol'),
    ('Other / Specialty', 'Glycols & Coolants', 'Antifreeze / Coolant'),
    ('Other / Specialty', 'Glycols & Coolants', 'Heat Transfer Fluid'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Methanol'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Ethanol'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Isopropyl Alcohol'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Acetone'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Mineral Spirits'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Paint Thinner'),
    ('Other / Specialty', 'Solvents & Alcohols', 'Mixed Solvents'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Acid Solution'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Caustic / Alkaline Solution'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Bleach / Hypochlorite Solution'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Ammonia Solution'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Detergent / Surfactant Solution'),
    ('Other / Specialty', 'Acids, Bases & Cleaners', 'Chemical Wash Water'),
    ('Other / Specialty', 'Industrial Chemicals', 'Diesel Exhaust Fluid (DEF)'),
    ('Other / Specialty', 'Industrial Chemicals', 'Calcium Chloride Brine'),
    ('Other / Specialty', 'Industrial Chemicals', 'Magnesium Chloride Brine'),
    ('Other / Specialty', 'Industrial Chemicals', 'Salt Brine'),
    ('Other / Specialty', 'Industrial Chemicals', 'Dust Suppressant - General'),
    ('Other / Specialty', 'Industrial Chemicals', 'Fertilizer Solution'),
    ('Other / Specialty', 'Industrial Chemicals', 'Pesticide / Herbicide Mix'),
    ('Other / Specialty', 'Industrial Chemicals', 'Unknown Chemical Liquid'),
    ('Other / Specialty', 'Industrial Chemicals', 'Unknown Chemical Sludge'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Paint / Coating Waste'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Paint Booth Sludge'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Resin / Polymer Waste'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Latex Waste'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Ink / Dye Waste'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Adhesive / Glue Waste'),
    ('Other / Specialty', 'Coatings, Resins & Manufacturing', 'Metalworking Fluid'),
    ('Other / Specialty', 'Ash, Sludge & Solids', 'Fly Ash'),
    ('Other / Specialty', 'Ash, Sludge & Solids', 'Bottom Ash'),
    ('Other / Specialty', 'Ash, Sludge & Solids', 'Wood Ash'),
    ('Other / Specialty', 'Ash, Sludge & Solids', 'Industrial Sludge'),
    ('Other / Specialty', 'Construction & Mineral Slurries', 'Concrete Washout'),
    ('Other / Specialty', 'Construction & Mineral Slurries', 'Cement / Grout Slurry'),
    ('Other / Specialty', 'Construction & Mineral Slurries', 'Mine Water'),
    ('Other / Specialty', 'Construction & Mineral Slurries', 'Tailings Water')
    ) as v(group_name, section_name, name)
  loop
    if not exists (
      select 1
      from public.mallard_classifications c
      where lower(btrim(c.group_name)) = lower(btrim(r.group_name))
        and lower(btrim(c.section_name)) = lower(btrim(r.section_name))
        and lower(btrim(c.name)) = lower(btrim(r.name))
    ) then
      perform public.mallard_create_classification_auto(
        r.name,
        r.group_name,
        r.section_name,
        null
      );
    end if;
  end loop;
end
$$;
